# Configuration of kube-diagrams
clusters:
  - label: grafana_dashboard
    title: Grafana Dashboard
    recommended: false
    graph_attr:
      bgcolor: tomato
  - label: grafana_datasource
    title: Grafana Data Source
    recommended: false
    graph_attr:
      bgcolor: tomato
diagram: # Customization of generated diagrams
  edges: # Add following custom edges
    - description: The Grafana test pod calls the Grafana service to test it
      from: kube-prometheus-stack-grafana-test/default/Pod/v1
      to: kube-prometheus-stack-grafana/default/Service/v1
      color: brown
      xlabel: test
    - description: The patch job updates the validating webhook configuration
      from: kube-prometheus-stack-admission-patch/default/Job/batch/v1
      to: kube-prometheus-stack-admission/ValidatingWebhookConfiguration/admissionregistration.k8s.io/v1
      color: black
      taillabel: update
      style: dotted
    - description: The patch job updates the mutating webhook configuration
      from: kube-prometheus-stack-admission-patch/default/Job/batch/v1
      to: kube-prometheus-stack-admission/MutatingWebhookConfiguration/admissionregistration.k8s.io/v1
      color: black
      taillabel: update
      style: dotted
